
# Image Classification ( Cat and Dog Classification)------------------------

path: C:/Users/HP/Desktop/Python/Dog and Cat Image classifier
train: C:/Users/HP/Desktop/Python/Dog and Cat Image classifier/train
val: C:/Users/HP/Desktop/Python/Dog and Cat Image classifier/test
nc: 2
